//PEREZ_PEREA_HARRY_ANTONIO_0222220035

package Game;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class Cronometro extends JFrame {

    int miliseg = 0;
    int segundos = 0;
    int minutos = 0;
    boolean estado;

    public Cronometro(boolean estado) {
        this.estado = estado;
    }
    
    public Cronometro() {
        initComponents(); 
        Calculo();
        this.setTitle("Cronometro");
        
    }

    public void setMiliseg(int miliseg) {
        this.miliseg = miliseg;
    }

    public void setSegundos(int segundos) {
        this.segundos = segundos;
    }

    public void setMinutos(int minutos) {
        this.minutos = minutos;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cronometro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        cronometro1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        cronometro1.setText("00:00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(cronometro1)
                .addGap(124, 124, 124))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(cronometro1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>                        

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
 
    private void Calculo(){
                    
          
     Thread hilo = new Thread(){
         
       public void run(){
               
           while(true){
           
               if(estado==true){
                   
                   try{
                       
                       sleep(1);
                       
                      if(miliseg>=1000){
                          
                          miliseg = 0;
                          segundos++;
                          
                          
                      } 
                      if(segundos>=60){
                          
                          miliseg=0;
                          segundos =0;
                          minutos++;
                          
                              
                      }
                      cronometro1.setText(minutos+" : "+segundos+" : "+miliseg);
                      miliseg++;
                      
                   }catch(Exception e){}                  
                   
               }else{
                   
                   break;
               }
           
           
           
           }

       }  
   
     };

     hilo.start();
    }        
    // Variables declaration - do not modify                     
    private JLabel cronometro1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    // End of variables declaration                   
}
